spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isswa
    username: isswa
    password: isswa
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: mysql
      username: isswa
      password: isswa
